FROM python:3.7

USER root

RUN pip3 install jupyter
RUN pip3 install jupyterlab
RUN pip3 install pandas
RUN pip3 install matplotlib
RUN pip3 install seaborn
RUN pip3 install torch --extra-index-url https://download.pytorch.org/whl/cpu
CMD jupyter lab --allow-root --ip=0.0.0.0 --port=5050

# Instructions:
# $ docker system prune -a
# $ docker build --file ./chapter-10/DockerFile -t chap10 .
# $ docker image ls
# $ docker run --publish=5050:5050 --volume ${PWD}/chapter-10:/chapter-10 chap10

# Then inside the docker container run:
# $ jupyter notebook --allow-root --ip=0.0.0.0
# $ jupyter lab --allow-root --ip=0.0.0.0
